# Bar For GlazeWM
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: True
watch_config: True
debug: False
update_check: False
# komorebi:
#   start_command: "komorebic start --whkd"
#   stop_command: "komorebic stop --whkd"
#   reload_command: "komorebic stop --whkd && komorebic start --whkd"
# glazewm:
#   start_command: "glazewm.exe start"
#   stop_command: "glazewm.exe command wm-exit"
#   reload_command: "glazewm.exe command wm-exit && glazewm.exe start"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 4
      left: 4
      bottom: 5
      right: 4
    widgets:
      left: [
          "home",
          "komorebi_workspaces",
          "komorebi_active_layout",
          "glazewm_workspaces",
          "glazewm_tiling_direction",
          "taskbar",
          #"komorebi_stack",
          "active_window",
          "traffic",
        ]
      center: ["clock", "apps"]
      right:
        [
          "cava",
          "media-cosmic",
          "cpu",
          "memory",
          "weather-acr",
          "volume-acr",
          "wallpapers",
          "brightness",
          "language",
          "power_menu",
        ]
widgets:
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span class='download'>\uea9a {download_speed}</span>|<span class='upload'>{upload_speed} \ueaa1</span>"
      update_interval: 1000
      menu:
        round_corners: true
        alignment: "center"
        direction: "down"
        offset_top: 6
        border_color: "None"
      callbacks:
        on_left: "toggle_menu"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 5
        offset: [0, 0]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 14
      gradient: 0
      reverse: 0
      sensitivity: 100
      foreground: "#89b4fa"
      gradient_color_1: "#74c7ec"
      gradient_color_2: "#89b4fa"
      gradient_color_3: "#cba6f7"
      bars_number: 14
      bar_spacing: 2
      bar_width: 4
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf47d"
      label_expanded: "\uf460"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      tooltip: true
  media-cosmic:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_play_pause"
        on_right: "toggle_label"
      max_field_size:
        label: 15
        label_alt: 15
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: true
      thumbnail_edge_fade: true
      thumbnail_padding: 32
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"
        separator: " "
        label_padding: 2
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 80
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "Brightness {percent}%"
      scroll_step: 10
      tooltip: true
      hide_unsupported: true
      brightness_toggle_level: [0, 25, 50, 75, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
          "\udb80\udcde", # Icon for 0-25% brightness
          "\udb80\udcdd", # Icon for 26-50% brightness
          "\udb80\udcdf", # Icon for 51-75% brightness
          "\udb80\udce0", # Icon for 76-100% brightness
        ]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
      progress_bar:
        enabled: false
        position: left
        size: 20
        thickness: 2
        color: "#57948a"
        animation: True
      callbacks:
        on_left: "toggle_brightness_menu"
        on_right: "toggle_label"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[layout_name]}"
      label_alt: "{lang[full_layout_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: "User Home", path: "~" }
        - { title: "Download", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "None"
      round_corners_type: "small"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 30
        exclude: []
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: " Shafin's Desktop"
      label_icon: false
      label_icon_size: 14
      max_length: 12
      max_length_ellipsis: ".."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %I:%M %p}"
      label_alt: "{%A, %d %B %Y %I:%M:%S}"
      timezones: []
      calendar:
        alignment: "center"
        border_color: "None"
        offset_top: 6
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      #label_workspace_btn: "\udb81\udc3d"
      #label_workspace_populated_btn: "\udb81\udc3e"
      label_workspace_btn: "{name}"
      label_workspace_populated_btn: "{name}"
      label_workspace_active_btn: "{name}"
      label_default_name: "{index}"
      label_float_override: " "
      enable_scroll_switching: true
      reverse_scroll_direction: true
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: true
      animation: true
      app_icons:
        {
          "enabled_populated": false,
          "enabled_active": false,
          "size": 16,
          "max_icons": 0,
          "hide_label": false,
          "hide_duplicates": true,
          "hide_floating": false,
        }
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
          "scrolling",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        "scrolling": "SCROLL"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        tiling: "TILING"
        paused: "PAUSED"
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true
      callbacks:
        on_right: "next_layout"
        on_middle: "toggle_monocle"
        on_left: "toggle_layout_menu"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_free}"
      label_alt: "<span>\uf4bc</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  volume-acr:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  weather-acr:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "1e6138c840424138be1141355252309" # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Dhaka, BD" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        # snowyIcyDay: "\udb81\udd98"
        # snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "1e6138c840424138be1141355252309"
      update_interval: 600
      hide_decimal: true
      location: "Dhaka, BD"
      callbacks:
        on_left: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]

  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - icon: "\uf422"
          launch: "C:\\Users\\joy11\\AppData\\Local\\FlowLauncher\\Flow.Launcher.exe"

        - icon: "󱞁"
          launch: "notepad"

        - icon: ""
          launch: "C:\\Program Files (x86)\\TickTick\\TickTick.exe"

        - icon: "\uf489"
          launch: "wt"

        - icon: "\ued38"
          launch: "C:\\Users\\joy11\\AppData\\Local\\Programs\\BeeperTexts\\Beeper.exe"

        - icon: ""
          launch: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: env
      max_notification: 30
      only_unread: false
      max_field_size: 54
      update_interval: 60
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      show_only_visible: false
      strict_filtering: false
      animation:
        enabled: false
      preview:
        enabled: True
        width: 240
        delay: 400
        padding: 8
        margin: 8
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      callbacks:
        {
          "on_right": "toggle_window",
          "on_left": "do_nothing",
          "on_middle": "close_app",
        }

  ai:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb81\ude74</span>"
      label_alt: "\udb81\ude74"
      class_name: "ai-widget"
      callbacks:
        on_left: "exec cmd.exe /c start \"C:\\Program Files\\Mozilla Firefox\\firefox.exe\" https://platform.openai.com/playground/chat?models=gpt-4o"
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "D:\\Collection\\wallpapers\\cycle\\Dark"
      change_automatically: true
      update_interval: 1800
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: false
        orientation: "portrait"
        image_spacing: 5
        lazy_load: false
        lazy_load_delay: 2
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true

  komorebi_stack:
    type: "komorebi.stack.StackWidget"
    options:
      label_offline: "Offline"
      label_window: ""
      label_window_active: ""
      label_no_window: ""
      label_zero_index: false
      show_icons: "always"
      icon_size: 16
      max_length: 1
      max_length_active: 5
      max_length_ellipsis: ".."
      hide_if_offline: false
      show_only_stack: false
      animation: false
      enable_scroll_switching: true
      container_shadow:
        enabled: false
        color: "#000000"
        offset: [0, 1]
        radius: 2
      btn_shadow:
        enabled: false
        color: "#000000"
        offset: [0, 1]
        radius: 2
      label_shadow:
        enabled: false
        color: "#000000"
        offset: [0, 1]
        radius: 2

  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "\uf501 New Task"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true
      enable_scroll_switching: true
      btn_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [1, 1]
      app_icons:
        enabled_populated: false
        enabled_active: false
        size: 16
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
      animation: false

      # By default workspace names are fetched from GlazeWM and "display_name" option takes priority over "name".
      # However, you can customize populated and empty labels here using {name} and {display_name} placeholders if needed.
      # {name} will be replaced with workspace name (index) from GlazeWM.
      # {display_name} will be replaced with workspace display_name from GlazeWM.

      # populated_label: "{name} {display_name} \uebb4"
      # empty_label: "{name} {display_name} \uebb5"
