general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  #startup_commands: ["shell-exec zebar"]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  #shutdown_commands: ["shell-exec taskkill /IM zebar.exe /F"]
  # hello

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "monitor_focus"

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: "cloak"

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: true

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: "6px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "4px"
    right: "6px"
    bottom: "6px"
    left: "6px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#859bc8"
      #color: "#9d7cbd"

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: "square"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: "#a1a1a1"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style:
        "rounded"
        # Change the transparency of the window.
    transparency:
      enabled: true
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: "100%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true
      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false
      outer_gap:
        top: "10px"
        right: "10px"
        bottom: "10px"
        left: "10px"
      border:
        enabled: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: "0"
    display_name: "N"
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "10"
    display_name: "G"
  - name: "11"
    display_name: "C"

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: "zebar" }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: "TickTick" }
      - window_process: { equals: "Vowen" }
      - window_process: { equals: "PasteBar" }
      - window_process: { equals: "Wispr Flow" }
      - window_process: { equals: "spacedeskService" }
      - window_process: { equals: "Install VALORANT" }
      - window_process: { equals: "Install VALORANT (1)" }
      - window_process: { equals: "Install VALORANT (2)" }
      - window_process: { equals: "Install VALORANT (3)" }
      - window_process: { equals: "Install VALORANT (4)" }
      - window_process: { equals: "spacedeskServiceTray" }
      - window_process: { equals: "easeus.voicewave.exe" }
      - window_process: { equals: "CapCut" }
      #- window_process: { equals: "explorer" }
      - window_process: { equals: "Notepad" }
      - window_process: { equals: "RiotClientServices.exe" }
      - window_process: { equals: "RiotClientSerivces" }
      - window_process: { equals: "Taskmgr" }
      - window_process: { equals: "ChatGPT" }
      - window_process: { equals: "WizTree64" }
      - window_process: { equals: "Mechvibes" }
      - window_title: { equals: "Windhawk" }
      - window_title: { equals: "Focus Timer" }
      - window_title: { equals: "SteelSeries GG" }
      - window_title: { equals: "spacedesk Driver Console" }
      - window_title: { equals: "EaseUS VoiceWave" }
      - window_process: { equals: "DubbingAI" }
      - window_process: { equals: "SystemSettings" }
      #- window_title: { equals: "Settings" }
      - window_process: { equals: "Install VALORANT" }
      - window_process: { equals: "Cold Turkey Blocker" }
      - window_process: { equals: "FxSound" }
      - window_process: { equals: "MSPCManager" }
      - window_process: { equals: "SnippingTool" }
      - window_process: { equals: "procexp64" }
      - window_process: { equals: "PowerToys.ColorPickerUI.exe" }
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }

  - commands: ["set-floating"]
    match:
      - window_process: { equals: "PasteBar" }
      - window_process: { equals: "PowerToys" }
      - window_process: { equals: "Discord" }
      - window_process: { equals: "TickTick" }
      - window_process: { equals: "RevoUninPro" }
      - window_process: { equals: "FastKeys" }
      - window_process: { equals: "Telegram" }
      - window_process: { equals: "Beeper" }
      - window_title: { equals: "WhatsApp" }
      - window_title: { equals: "Instagram" }

  - commands: ["set-tiling"]
    match:
      - window_process: { equals: "msedge" }
      - window_process: { equals: "xodopdfreader" }
      - window_process: { equals: "YouTube Music" }
      - window_process: { equals: "obs64" }
      - window_process: { equals: "vlc" }
      - window_process: { equals: "Figma" }
      - window_process: { equals: "Code" }
      - window_process: { equals: "anki" }
      - window_process: { equals: "Anytype" }
      - window_process: { equals: "Anytype" }
      - window_process: { equals: "Cursor" }
      - window_process: { equals: "WindowsTerminal" }
      - window_process: { equals: "powershell" }
      - window_process: { equals: "Obsidian" }
      - window_process: { equals: "cmd" }
      - window_process: { equals: "chrome" }

  - commands: ["move --workspace 0", "focus --workspace 0"]
    match:
      - window_process: { equals: "Obsidian" }
      #- window_title: { contains: "Notion - Home | Note Taking" }
      - window_title: { regex: "^Notion - Home | Note taking.*$" }

  - commands: ["move --workspace 10", "focus --workspace 10"]
    match:
      - window_process: { equals: "VALORANT" }
      - window_process: { equals: "obs64" }
      - window_process: { equals: "AimLab_tb" }
      - window_process: { equals: "VALORANT-Win64-Shipping" }
      - window_title: { equals: "VALORANT" }

  - commands: ["move --workspace 11", "focus --workspace 11"]
    match:
      - window_process: { equals: "YouTube Music" }
      - window_process: { equals: "Beeper" }
      - window_process: { equals: "Telegram" }
      - window_title: { equals: "WhatsApp" }
      - window_title: { equals: "Instagram" }
      - window_title: { equals: "YouTube Music" }
      - window_title: { equals: "Spotify" }
      - window_process: { equals: "Discord" }

  - commands: ["toggle-floating"]
    match:

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  # =============== vim =======================
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["j", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["i", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["k", "down"]
      # =============== vim =======================
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]
  # the name 'resize'.

keybindings:
  #Launch Programs
  #- commands: ["shell-exec wt.exe"]
  #  bindings: ["alt+t"]
  # =============== vim =======================
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+j"]
  - commands: ["focus --direction down"]
    bindings: ["alt+k"]
  - commands: ["focus --direction up"]
    bindings: ["alt+i"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+j"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+k"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+i"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l"]
  # =============== vim =======================

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+["]
  - commands: ["resize --width +2%"]
    bindings: ["alt+]"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+shfit+["]
  - commands: ["resize --height -2%"]
    bindings: ["alt+shift+]"]

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Change the focused window to be fullscreen.
  #- commands: ["toggle-fullscreen"]
  #  bindings: ["alt+shift+f"]

  # Minimize focused window.
  #- commands: ["toggle-minimized"]
  #  bindings: ["alt+d"]

  # Close focused window.
  #- commands: ["close"]
  #  bindings: ["ctrl+q"]

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+shift+v"]

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ["wm-cycle-focus"]
    bindings: ["alt+v"]

  # Change the focused window to be floating.
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+q"]

  # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+w"]

  # Change the focused window to be ignored.
  - commands: ["ignore"]
    bindings: ["alt+ctrl+e"]

  # Kill GlazeWM process safely.
  #- commands: ["wm-exit"]
  #  bindings: ["alt+shift+e"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["alt+s"]
  - commands: ["focus --prev-workspace"]
    bindings: ["alt+a"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 0"]
    bindings: ["alt+`"]
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]
  - commands: ["focus --workspace 10"]
    bindings: ["alt+G"]
  - commands: ["focus --workspace 11"]
    bindings: ["alt+c"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move --workspace 0", "focus --workspace 0 "]
    bindings: ["alt+shift+`"]
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
  - commands: ["move --workspace 10", "focus --workspace 10"]
    bindings: ["alt+shift+G"]
  - commands: ["move --workspace 11", "focus --workspace 11"]
    bindings: ["alt+shift+c"]

  # Focus the workspace that last had focus
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+0"]

  # Move to the next/previous workspace that last had focus
  - commands: ["move --recent-workspace", "focus --recent-workspace"]
    bindings: ["alt+shift+0"]

  # Move the next/previous workspace defined in `workspaces` config.
  - commands: ["move --next-workspace", "focus --next-workspace"]
    bindings: ["alt+shift+s"]
  - commands: ["move --prev-workspace", "focus --prev-workspace"]
    bindings: ["alt+shift+a"]
